version: "3"

services:
  alert-web:
    build:
      context: .
    environment:
      NODE_ENV: dev
      PORT: 3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "wait-on --timeout 1000 tcp:${PGHOST}:${PGPORT} && node index.js"

