name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        PORT: 3000
        HOST: "0.0.0.0"
        ENV: "local"
        FORCE_HTTPS: false
        PHASE_BANNER_TAG: local
        PHASE_BANNER_HTML: "This is a TEST service - you will not issue alerts"
        PUBLISHER_ID: 92895119-cb53-4012-8eb9-173a22f2db7a
        SERVICE_ID: ecbb79cc-47f5-4bb0-ad0c-ca803b671cfb
        HOME_PAGE: http://localhost:3000
        DOCUMENTATION_HOME_PAGE: http://localhost:3000/documentation
        COOKIE_PASSWORD: ${{ secrets.COOKIE_PASSWORD }}
        COOKIE_IS_SECURE: false
        AD_CLIENT_ID: ${{ secrets.AD_CLIENT_ID }}
        AD_CLIENT_SECRET: ${{ secrets.AD_CLIENT_SECRET }}
        AD_TENANT: ${{ secrets.AD_TENANT }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        BROKER_URL: ${{ secrets.BROKER_URL }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-2
        BUCKET_NAME: xws-files-dev

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build --if-present
    - uses: citizen-of-planet-earth/cf-cli-action@master
      with:
        cf_api: https://api.london.cloud.service.gov.uk
        cf_username: ${{ secrets.CF_USERNAME }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: defra-next-warning-system
        cf_space: sandbox
        command: push "xws-alert-web-sandbox"

