name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        PORT: 3000
        HOST: "0.0.0.0"
        ENV: "local"
        FORCE_HTTPS: false
        PUBLISHER_ID: 92895119-cb53-4012-8eb9-173a22f2db7a
        SERVICE_ID: ecbb79cc-47f5-4bb0-ad0c-ca803b671cfb
        HOME_PAGE: http://localhost:3000
        COOKIE_PASSWORD: ${{ secrets.COOKIE_PASSWORD }}
        COOKIE_IS_SECURE: false
        AD_CLIENT_ID: ${{ secrets.AD_CLIENT_ID }}
        AD_CLIENT_SECRET: ${{ secrets.AD_CLIENT_SECRET }}
        AD_TENANT: ${{ secrets.AD_TENANT }}
        DYNAMODB_TABLE_NAME: alert-db
